"""Migration initiale

Revision ID: c7b1f7fc276b
Revises: 
Create Date: 2026-07-03 14:42:58.295266

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7b1f7fc276b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sites',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('nom', sa.String(length=255), nullable=False),
    sa.Column('url', sa.String(length=255), nullable=False),
    sa.Column('title_selector', sa.String(length=255), nullable=True),
    sa.Column('description_selector', sa.String(length=255), nullable=True),
    sa.Column('deadline_selector', sa.String(length=255), nullable=True),
    sa.Column('link_selector', sa.String(length=255), nullable=True),
    sa.Column('type_site', sa.String(length=100), nullable=True),
    sa.Column('actif', sa.Boolean(), nullable=True),
    sa.Column('frequence_scraping', sa.Integer(), nullable=True),
    sa.Column('derniere_execution', sa.DateTime(), nullable=True),
    sa.Column('methode_scraping', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('nom', sa.String(length=50), nullable=False),
    sa.Column('prenom', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('datetime_inscription', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('bourses',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('nom', sa.String(length=255), nullable=False),
    sa.Column('organisme', sa.String(length=255), nullable=True),
    sa.Column('montant', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('niveau', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('pays', sa.String(length=100), nullable=True),
    sa.Column('deadline', sa.Date(), nullable=True),
    sa.Column('type', sa.String(length=100), nullable=True),
    sa.Column('lien_officiel', sa.String(length=255), nullable=True),
    sa.Column('site_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users_bourses',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('bourse_id', sa.String(length=36), nullable=False),
    sa.Column('datetime_interet', sa.DateTime(), nullable=True),
    sa.Column('statut', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['bourse_id'], ['bourses.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'bourse_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_bourses')
    op.drop_table('bourses')
    op.drop_table('users')
    op.drop_table('sites')
    # ### end Alembic commands ###
